Output demo.gif
Set FontSize 26
Set Theme "Dracula"
Set Width 1200
Set Height 600

Sleep 500ms

Type "deci demo.md"
Sleep 500ms

Enter
Sleep 500ms

Type "# This is deci"
Sleep 1s
Right 2
Sleep 300ms
Ctrl+Right
Sleep 200ms
Ctrl+Right
Sleep 300ms
Type "second-to-"
Sleep 500ms

Ctrl+Right
Sleep 50ms
Ctrl+Right
Sleep 50ms
Ctrl+Right
Sleep 300ms

Type " ;-)"
Sleep 500ms
Down 2
Ctrl+Left
Sleep 50ms
Ctrl+Left
Sleep 50ms
Ctrl+Left
Sleep 50ms
Ctrl+Left
Sleep 50ms
Ctrl+Left
Sleep 50ms
Left
Sleep 100ms
Right
Sleep 200ms
Type "**"
Sleep 200ms
Right 3
Type "**"
Sleep 800ms
Down 6
Sleep 300ms
Enter 2
Sleep 200ms
Type "here's what this looks in the preview"
Sleep 500ms

Ctrl+P
Sleep 2s

Ctrl+P
Sleep 500ms
Down 14
Enter
Sleep 500ms
Type "enjoy!"

Sleep 1s
Ctrl+C
