Set FontSize 20
Set Theme "Dracula"
Set Width 1440
Set Height 810
Set CursorBlink false

Hide
Type "deci"
Enter
Show
Sleep 0.5s
Screenshot web/uploads/empty.png
Sleep 0.5s

Hide
Sleep 0.5s
Ctrl+H
Show
Sleep 0.5s
Screenshot web/uploads/help.png
Sleep 0.5s

Hide
Ctrl+C
Sleep 0.5s
Type "deci main.go"
Enter
Show
Sleep 0.5s
Screenshot web/uploads/code.png
Sleep 0.5s

Hide
Ctrl+C
Sleep 0.5s
Type "deci README.md"
Enter
Show
Sleep 0.5s
Screenshot web/uploads/readme.png
Sleep 0.5s

Hide
Sleep 0.5s
Ctrl+P
Show
Sleep 0.5s
Screenshot web/uploads/preview.png
Sleep 0.5s

Hide
Ctrl+C
Sleep 1s
