Set FontSize 20
Set Theme "Dracula"
Set Width 1440
Set Height 810

Hide
Type "deci"
Enter
Show
Sleep 0.5s
Screenshot web/uploads/empty.png

Hide
Sleep 0.5s
Ctrl+H
Show
Sleep 0.5s
Screenshot web/uploads/help.png

Hide
Ctrl+C
Type "deci main.go"
Enter
Show
Sleep 0.5s
Screenshot web/uploads/code.png

Hide
Ctrl+C
Type "deci README.md"
Enter
Show
Sleep 0.5s
Screenshot web/uploads/readme.png

Hide
Sleep 0.5s
Ctrl+P
Show
Sleep 0.5s
Screenshot web/uploads/preview.png

Hide
Ctrl+C
